name: ci

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/go-setup@v2
        with:
          go-version: '17'
          
      - name: Setup constant
        run: |
          pull_req_url=${{github.event.client_payload.pull_request_url}}
          token=${{github.event.client_payload.token_csrf}}
          task_id=1
          adapter_op=${{github.event.client_payload.adapter_url}}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo  |
          echo 
          
