name: ci

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        pull_req_url: ${{github.event.client_payload.pull_request_url}}
        token: ${{github.event.client_payload.token_csrf}}
        task_id: 0
        adapter_op: ${{github.event.client_payload.adapter_url}}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
          
       



      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: always()
        run: |
          echo ${{ env.pull_req_url}} 
          echo ${{ env.token}} 
          echo ${{ env.task_id}} 
          echo ${{ env.adapter_op}} 
        shell: run
