name: ci

on:
  repository_dispatch:
    type: [ci-event]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
        pull_req_url: ${{github.event.client_payload.pull_request_url}}
        token: ${{github.event.client_payload.token_csrf}}
        task_score: 0
        task_id: ${{github.event.client_payload.task_id}}
        adapter_url: ${{github.event.client_payload.adapter_url}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
          
      - name: git clone
        run:  |
          tree
          sudo git clone ${{env.pull_req_url}} ci
          tree       
          
      - name: Install dependences
        working-directory: ci
        run: go mod download
        
      - name: Delete old test
        run: |
          tree
          sudo rm ci/math/math_test.go
          tree
        
        
      - name: Set new test
        run: |
          tree
          sudo mv math_test.go ci/math/math_test.go
          tree
        
        
      - name: Test TestSquare
        working-directory: ci
        if: always() && ${{env.task_id}} > 0
        run:  |
          go test math/math_test.go -v -run TestSquare
          echo "task_score=$(expr ${{env.task_score}} + 1)" >> "$GITHUB_ENV"
          
      - name: Test TestCube
        working-directory: ci
        if: always() && ${{env.task_id}} > 1
        run:  |
          go test math/math_test.go -v -run TestCube
          echo "task_score=$(expr ${{env.task_score}} + 1)" >> "$GITHUB_ENV"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: always()
        run: |
          echo ${{ env.pull_req_url}} 
          echo ${{ env.token}} 
          echo ${{ env.task_score}} 
          echo ${{ env.adapter_url}} 
