name: ci

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '17'
          
      - name: Setup constant
        run: |
          pull_req_url=${{github.event.client_payload.pull_request_url}}
          token=${{github.event.client_payload.token_csrf}}
          task_id=0
          adapter_op=${{github.event.client_payload.adapter_url}}



      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: always()
        run: |
          echo $pull_req_url
          echo $token
          echo $task_id
          echo $adapter_op
          
