name: ci

on:
  repository_dispatch:
    type: [ci-event]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
        pull_req_url: ${{github.event.client_payload.pull_request_url}}
        token: ${{github.event.client_payload.token_csrf}}
        task_score: 0
        adapter_url: ${{github.event.client_payload.adapter_url}}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          
      - name: git clone
        run:  |
          tree
          git clone ${{env.pull_req_url}} .
        
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
        
        
      - name: delete old test
        run: |
          tree
          rm math/math_test.go
        
        
      - name: set new test
        run: mv math_test.go math/math_test.go
        
      - name: test
        run:  |
          go test math/math_test.go
          echo "task_score=$(expr ${{env.task_score}} + 1)" >> "$GITHUB_ENV"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        if: always()
        run: |
          echo ${{ env.pull_req_url}} 
          echo ${{ env.token}} 
          echo ${{ env.task_score}} 
          echo ${{ env.adapter_url}} 
